### ISSUE TITLE
Mantid Testing Data Should be Available Somewhere Other Than the Linode

### ISSUE THREAD

**Issue by cailafinn** [mantidproject/dockerfiles#98]
## Contribution to Target

Timeouts occur when linode throttles download. Was seen when many nodes needed to download the data from scratch after being re-generated. Providing a version available inside the STFC network will be far faster to download and far less likely to be throttled. 

## Issue Description

Initial improvement to allow easier access to the testing data. 

[Martyn's](https://github.com/martyngigg/dv-data-platform-poc/tree/main/ansible/playbooks/minio) [repos](https://github.com/martyngigg/scd-cloud-workshop/tree/main/advanced/ansible/hello_world) may be useful here as a starting point. 

## Tasks
- [ ] Create a new machine (host) on Openstack with a floating IP address. (Note, this will say external, but it won't be unless the firewall is configured to allow access external to the STFC network.
- [ ] Write an ansible script to perform the following:
  - [ ] Create a directory on the host to hold the external data. 
  - [ ] Create a `crontab` job to `rsync` the data from the linode into this new directory every few minutes.
  - [ ] Spin up a docker container with the default `nginx` image (example [here](https://github.com/mantidproject/dockerfiles/blob/main/jenkins-node/mantid-builder/bin/deploy_external_data.sh)
  - [ ] Mount the external data directory from the host inside this docker container.

## Additional Improvements
- [ ] Creation of the node included in ansible script by using the Openstack API.
